
 #--------------------------------------------------------TASK 4---------------------------------------------------#
 #USING AGGREGATE FUNCTION : COUNT
 SELECT COUNT(GENRE)
FROM BOOKS
WHERE GENRE LIKE '%C%' '%N%';
SELECT COUNT(MEMBER_ID),JOIN_DATE
FROM MEMBERS
WHERE MEMBER_NAME IS NOT NULL
GROUP BY JOIN_DATE
HAVING COUNT(MEMBER_ID)!=5005
ORDER BY COUNT(MEMBER_ID) DESC;
SELECT COUNT(BOOKID),MEMBER_ID,BORROW_ID
FROM BORROW_BOOKS
GROUP BY MEMBER_ID,BORROW_ID
HAVING COUNT(BOOKID)>1
ORDER BY COUNT(BOOKID) DESC;
#SUM
SELECT SUM(Available_copies),BOOKID,TITLE
 FROM BOOKS 
 WHERE BOOKID BETWEEN 0005 AND 0020
 GROUP BY BOOKID,TITLE
 HAVING SUM(AVAILABLE_COPIES)<20;
SELECT SUM(MEMBER_NAME),MEMBER_ID,JOIN_DATE
FROM MEMBERS
GROUP BY MEMBER_ID,JOIN_DATE
HAVING SUM(MEMBER_ID)>5015;
#AVG
SELECT AVG(BORROW_ID),BOOKID,MEMBER_ID
FROM BORROW_BOOKS
GROUP BY BOOKID,MEMBER_ID;
SELECT AVG(PUBLISHED_YEAR),TITLE,AUTHOR
FROM BOOKS
GROUP BY TITLE,AUTHOR
HAVING  AVG(PUBLISHED_YEAR) IS NOT NULL
ORDER BY AVG(PUBLISHED_YEAR);
SELECT AVG(MEMBER_ID),MEMBER_NAME
FROM MEMBERS
WHERE MEMBER_NAME LIKE '%A'
GROUP BY MEMBER_ID,MEMBER_NAME
HAVING MEMBER_ID>5020;

#FIRST() AND LAST()
SELECT MEMBER_NAME
FROM MEMBERS
LIMIT 4;
SELECT TITLE,AUTHOR,BOOKID
FROM BOOKS
ORDER BY AUTHOR,BOOKID DESC
LIMIT 4;
#MAX()
SELECT MAX(BOOKID),TITLE,AUTHOR
FROM BOOKS
GROUP BY BOOKID,TITLE,AUTHOR
HAVING MAX(BOOKID)>10;




